version: '3'
services:
  mariadb:
    image: "mariadb:10.3.9"
    environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_USER=1bd3e0294da19198
    - MYSQL_DATABASE=1bd3e0294da19198
    - MYSQL_PASSWORD=iAlcDxokJhGvpxaK
    volumes:
    - ./mariadb-conf:/etc/mysql/conf.d
    - ./mariadb-initdb:/docker-entrypoint-initdb.d
    ports:
    - "3307:3306" #mariadb-port
    container_name: mariadb

  redis-cache:
    image: redis:4.0.11-alpine
    volumes:
    - ./redis-conf/redis_cache.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-cache
    sysctls:
      net.core.somaxconn: '511'

  redis-queue:
    image: redis:4.0.11-alpine
    volumes:
    - ./redis-conf/redis_queue.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-queue
    sysctls:
      net.core.somaxconn: '511'

  redis-socketio:
    image: redis:4.0.11-alpine
    volumes:
    - ./redis-conf/redis_socketio.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-socketio
    sysctls:
      net.core.somaxconn: '511'

  erpnext:
    image: docker.seibert-media.net/seibertmedia/erpnext:latest
    build:
      context: .
    volumes:
    - ./apps/seibertmedia:/home/frappe/bench-repo/apps/seibertmedia
    ports:
    - "8000:8000"
    - "9000:9000"
    environment:
    - ROOT_PASSWORD=123
    - ADMIN_PASSWORD=123
    - DB_HOST=mariadb
    - DB_NAME=1bd3e0294da19198
    - DB_PASSWORD=iAlcDxokJhGvpxaK
    - ENCRYPTION_KEY=vZUk5YjEeRdQkGWOFecw2TBFIvmxB7gJ7lZwIE3S9Ds
    - DEVELOPER_MODE=1
    extra_hosts:
    - "site1.local:127.0.0.1"
    stdin_open: true
    tty: true
    links:
    - redis-cache
    - redis-queue
    - redis-socketio
    - mariadb
    depends_on:
    - mariadb
    - redis-cache
    - redis-queue
    - redis-socketio
    container_name: erpnext
    command: ["bench","start"]
